apiVersion: v1
kind: Pod
metadata:
  name: ref-data-server
  namespace: ref-data-server
  labels:
    app: ref-data-server
spec:
  containers:
  - name: ref-data-server
    image: deepa17/flux-gitops-demo:1.0.2
    ports:
    - containerPort: 8001
    env:
    - name: CONTENT_TYPE
      value: application/json
